# Note: This is a configuration of the ChatControl plugin
# Official page: http://www.spigotmc.org/resources/chatcontrol.271/
# SLOVAK DEVELOPER FTW
# Supports color codes: & + 0 - F

# For configuration help visit: https://github.com/kangarko/ChatControl/blob/master/config.yml

Chat:
  Block_Duplicate_Messages: true
  # Block 75% similar messages.
  Block_Similar_Messages: true
  # When blocking duplicate message, should we strip UTF-8 special characters from it?
  # e.g messages "Hello" and "<<Hello!?!" will after this strip be detected as equals.
  # Which can lower spam and preventing users bypassing this check by adding some characters like ! ? etc.
  Strip_Unicode: true
  Message_Delay: 1
  Write_To_File: true
  Ignore_Players:
    - anonymouser1
  # Commands included in chat log.
  Include_Commands:
    - /tell
    - /msg
    - /r
    - /t
    - /w
    - /mail
    - /me
  # You need Essentials to enable it.  
  Notify_Player_When_Mentioned:
    # When enabled in chat the plugin is iterating over every online player, beware for lag on bigger servers.
    Enabled: false
    Enabled_In_Commands: true
    Only_Notify_When_Afk: false
    Sound: CHICKEN_EGG_POP
    # Type none to notify when using just his plain name.
    # By default you need to call him like @kangarko to play sound to him.
    In_Chat_When_Prefixed_With: "@"
    In_Commands:
      - /tell
      - /t
      - /msg
      - /m
      - /reply
      - /r
    
# Similar functionality as ChatManager, now a discontinued plugin that was part of the PermissionEx package.
# Disabled by default. *NOT* compatible with EssentialsChat *OR* other chat formatting plugins.
# You need to have PermissionEx installed.
Chat_Formatter:
  Enabled: false
  Message_Format: '%prefix%player:%suffix %message'
  Global_Message_Format: '%prefix%player%suffix &e%message'
  Ranged_Mode: false
  Chat_Range: 100.0

Messages:
  # Default - not handled by ChatControl; none - message will not shown. Or just write your own message .
  # Example: Join_Message: "&e&o%player &6just quit the game"
  # Variables: %player and %prefix
  Common:
    Join_Message: default
    Quit_Message: default
    Kick_Message: default

Grammar:
  Capitalize: 
    Enabled: true
    Minimum_Msg_Length: 5
  Insert_Dot: 
    Enabled: true
    Minimum_Msg_Length: 5

Commands:
  Block_Duplicate_Commands: true
  Block_Similar_Commands: true
  Strip_Unicode: true
  Command_Delay: 1
  Whitelist_Time:
    - tell
  Whitelist_Duplication:
    - tpa
    - spawn
    - home

Protect:
  Prevent_Tab_Complete: true

Signs:
  Advertising_Check: true
  # If false, plugin just disallow the text.
  Rewrite_Lines: true
  Rewrite_Text: "Advertising was:&4detected.:Please do not:advertise."
  # Check for signs text duplication. Fair players can get annoyed, deal with caution.
  Duplication_Check: false

Mute:
  Broadcast: true
  Disable:
    Join_Messages: true
    Quit_Messages: true
    Kick_Messages: true
    Death_Messages: true
  Disabled_Commands_During_Mute:
    - me
    - tell
    - msg
    - r
    
Clear:
  Broadcast: true
  Do_Not_Clear_For_Staff: false
  Amount_Of_Lines_To_Clear_In_Console: 300

Anti_Bot:
  Rejoin_Time: 4

Anti_Caps:
  Enabled: true
  Minimum_Message_Length: 5
  Total_Caps_Percentage: 50
  Caps_In_A_Row: 5
  Warn_Player: true
  Whitelist:
    - OMG
    - LOL
    - ROFL
    - WOW
    - LMFO

Anti_Swear:
  Enabled: true
  Enabled_In_Commands: true
  Command_Whitelist:
    - /register
    - /reg
    - /login
    - /l
  Block_Message: false
  # Send a message to player that sweared ? (Customizable below)
  Warn_Player: true
  Inform_Admins: true
  # Replace the word ? Block_Message must be false for this to work.
  Replace_Word: true
  # Note: This fully works only on regex expressions.
  Replacement: "****"
  # Use %player for player and %message for message.
  Custom_Command: none
  # Careful with Regular Expressions. Can broke the plugin!
  Word_List:
    - \bf(u|v)(c)(k|q)|\bf'ing|\bf(c)k\b
    - b(i|1|!)tch
    - \bpiss off
    - \bsuck
    - \bass\b
    - n(o)(o|0|00)b
    - l(o|0)(o)s(e|3)r
    - ".*p+u+s+s+(y|ies|y+s).*"

Anti_Ad:
  Enabled: true
  Enabled_In_Commands: true
  Command_Whitelist:
    - /register
    - /reg
    - /login
    - /l
    - /auction
    - //                   # Ignore WorldEdit.
  Inform_Admins: true
  Console_Message: true
  Broadcast: false
  Write_To_File: true
  # Filter based on RegEx improves the standard filters below. It replaces characters [,],(,) by default.
  Filter_Pre_Process: '[\(\[\]\)]'
  # Careful with the Regular Expressions. Random changing might blow of your server! 
  IP_Filter: '\b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b'
  # To add new domain (for example you want to "se" domain blocked) add the domain at the end like:  |eu|yourDomain
  Domain_Filter: '[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu)\b'
  Custom_Filter: none
  Custom_Command: none
  Whitelisted:
    IP:
      - 127.0.0.1
     #- Your.Server.Ip
    Domains:
      - youtube.com
      - google.com
     #- YourServerWebSite.com

Miscellaneous:
  Minimum_Players_To_Enable_Plugin: 0
  Block_Chat_Until_Moved: true
  Op_Has_Permissions: true
  # How long we should tolerate a regex to freeze the server? Can prevent some malformed regex to crash the server.
  RegEx_Timeout_Milis: 1500
  Automatically_Update_Config: true
  Check_For_Updates: true
  Download_Automatically: true
  Notify_New_Version: true
  Debug: false

Localization:
  # Use %prefix to add the prefix.
  Dupe_Message: "&cPlease do not repeat the same (or similar) message."
  Dupe_Command: "&cPlease do not repeat the same (or similar) command."
  Dupe_Sign: "&cPlease do not repeat the same text on signs."
  Time_Message: "&cPlease wait %time second(s) before your next message."
  Command_Message: "&cPlease wait %time second(s) before your next command."
  
  Ad_Message: "&7Please do not advertise other websites or IP adresses."
  Ad_Staff_Message: "&c%player might have advertised: &f%message "
  Ad_Broadcast_Message: "&c%player might have advertised! "
  Ad_Console_Message: "&c%player might have advertised: &f%message"
  
  Caps_Message: "&cDo not use so much CAPS LOCK!"
  
  Successful_Mute: "&7Chat was successfully muted."
  Successful_Unmute: "&7The chat is no longer muted."
  
  Broadcast_Mute: "%prefix &eChat was muted by %player!"
  Broadcast_Silent_Mute: "&cInitiated global chat mute."
  
  Broadcast_Unmute: "%prefix &eChat was unmuted by %player!"
  Broadcast_Silent_Unmute: "&cGlobal chat mute was cancelled."
  
  Broadcast_Clear: "%prefix &eChat was cleared by %player!"
  Broadcast_Silent_Clear: "&cThe game chat was cleared."
  
  Successful_Console_Clear: "%prefix &7Console was successfully cleared."
  Do_Not_Swear: "&cPlease do not swear, otherwise an action will be taken!"
  Swear_Admin_Message: "&c%player has sworn:&f %message"
  
  Cannot_Chat_While_Muted: "&7You cannot chat while the chat is muted!"
  Cannot_Command_While_Muted: "&7You cannot use this command while the chat is muted!"
  Cannot_Chat_Until_Moved: "&7You cannot chat until you move!"
  Cannot_Broadcast_Empty_Message: "&cMessage at %event is empty. No broadcast."
  
  Staff_Chat_Clear_Message: "&7^----- [ == &fChat was cleared by %player &7== ] -----^"
  Rejoin_Message: "&6Please wait &7%time second(s)&6 before logging in."
  Update_Needed: "&2A new version of &3ChatControl&2 is available.\n&2Current version: &f%current&2; New version: &f%new\n&2You can disable this notification in its config."
  Reload_Complete: "%prefix &2Reloading done. &7Beware: Reload might not be safe. In case of issues try restarting server."
  No_Permission: "&cInsufficient permission."
  
  Wrong_Args: "&cWrong arguments. Type &6/chc list&c for command list."
  Wrong_Parameters: "&cWrong parameters, available are: &7%params"
  
  Usage_Fake_Cmd: "%prefix Usage: /chatcontrol fake <&bjoin&f/&aleave&f>"
  
  Reason: "&7Reason:&f%reason"
  Prefix: "&8[&3ChatControl&8]&f"
  Console: "&4server"

Do_Not_Change_Version_Number: 4.5.7